plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.elmarto.lysy'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.elmarto.lysy.gate1'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '0.1-gate1'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
